In [232]:
import pandas as pd
import numpy as np

In [233]:
df = pd.read_csv("all_billionaires_1997_2024.csv")
df.tail()

C:\Users\USER-PC\AppData\Local\Temp\ipykernel_26396\2693829359.py:1: DtypeWarning: Columns (0: self_made) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("all_billionaires_1997_2024.csv")

,year,month,rank,net_worth,last_name,first_name,full_name,birth_date,age,gender,country_of_citizenship,country_of_residence,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
34506,2024,4,2692.0,1.0 B,Zhang,Hong,Zhang Hong,NaN,NaN,Female,China,China,Hangzhou,Energy,['Energy'],NaN,NaN,True,Decreased
34507,2024,4,2692.0,1.0 B,Zheng,Xiaodong,Zheng Xiaodong,1964-03-01,60.0,Male,China,China,Shanghai,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased
34508,2024,4,2692.0,1.0 B,Zhong,Sheng Jian,Zhong Sheng Jian,1958-03-03,66.0,Male,Singapore,Singapore,Singapore,Real Estate,['Real Estate'],NaN,NaN,True,Decreased
34509,2024,4,2692.0,1.0 B,Zhou,Junjie,Zhou Junjie,1968-07-20,55.0,Male,China,China,Hangzhou,Manufacturing,['Manufacturing'],NaN,NaN,True,NaN
34510,2024,4,2692.0,1.0 B,Zhu,Yiwen,Zhu Yiwen & family,1964-01-01,60.0,Male,China,China,Shanghai,Healthcare,['Healthcare'],NaN,NaN,True,Decreased

In [234]:
print(f"Shape: {df.shape}")

Shape: (34511, 19)

In [235]:
for col in df.columns:
    if df[col].dtype == "str": 
        print(f"Col Name: {col} || Datatype: {df[col].dtype} || Is null %: {df[col].isnull().mean()}")
    else: 
        print(f"Col Name: {col} || Datatype: {df[col].dtype} || Is null %: {df[col].isnull().mean()} || Mean : {df[col].mean()}")

Col Name: year || Datatype: int64 || Is null %: 0.0 || Mean : 2016.420011010982
Col Name: month || Datatype: int64 || Is null %: 0.0 || Mean : 3.4153458317637853
Col Name: rank || Datatype: float64 || Is null %: 0.0005215728318507143 || Mean : 940.6630910619546
Col Name: net_worth || Datatype: str || Is null %: 0.0
Col Name: last_name || Datatype: str || Is null %: 0.10689345426096028
Col Name: first_name || Datatype: str || Is null %: 0.10868998290400163
Col Name: full_name || Datatype: str || Is null %: 0.0
Col Name: birth_date || Datatype: str || Is null %: 0.12943699110428558
Col Name: age || Datatype: float64 || Is null %: 0.02161629625336849 || Mean : 63.065630090330224
Col Name: gender || Datatype: str || Is null %: 0.11095013184202139
Col Name: country_of_citizenship || Datatype: str || Is null %: 0.00026078641592535714
Col Name: country_of_residence || Datatype: str || Is null %: 0.02083393700559242
Col Name: city_of_residence || Datatype: str || Is null %: 0.02888933963084234
Col Name: business_category || Datatype: str || Is null %: 0.16927936020399292
Col Name: business_industries || Datatype: str || Is null %: 0.028686505751789285
Col Name: organization_name || Datatype: str || Is null %: 0.8632899655182406
Col Name: position_in_organization || Datatype: str || Is null %: 0.8538437020080554
Col Name: self_made || Datatype: object || Is null %: 0.10689345426096028 || Mean : 0.6316592044643436
Col Name: wealth_status || Datatype: str || Is null %: 0.21488800672249428

In [236]:
df_billionaire = df.drop(columns=["month", "last_name", "first_name", "country_of_residence"])
df_billionaire.tail()

,year,rank,net_worth,full_name,birth_date,age,gender,country_of_citizenship,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
34506,2024,2692.0,1.0 B,Zhang Hong,NaN,NaN,Female,China,Hangzhou,Energy,['Energy'],NaN,NaN,True,Decreased
34507,2024,2692.0,1.0 B,Zheng Xiaodong,1964-03-01,60.0,Male,China,Shanghai,Manufacturing,['Manufacturing'],NaN,NaN,True,Decreased
34508,2024,2692.0,1.0 B,Zhong Sheng Jian,1958-03-03,66.0,Male,Singapore,Singapore,Real Estate,['Real Estate'],NaN,NaN,True,Decreased
34509,2024,2692.0,1.0 B,Zhou Junjie,1968-07-20,55.0,Male,China,Hangzhou,Manufacturing,['Manufacturing'],NaN,NaN,True,NaN
34510,2024,2692.0,1.0 B,Zhu Yiwen & family,1964-01-01,60.0,Male,China,Shanghai,Healthcare,['Healthcare'],NaN,NaN,True,Decreased

In [237]:
df_billionaire["net_worth"] = df_billionaire["net_worth"].astype(str).str.split(" ").str[0].astype(float)
df_billionaire.head()

,year,rank,net_worth,full_name,birth_date,age,gender,country_of_citizenship,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
0,1997,NaN,2.0,Chatri Sophonpanich & family,1934-02-28,73.0,Male,Thailand,Bangkok,Finance and Investments,['Finance and Investments'],NaN,NaN,False,NaN
1,1997,NaN,1.8,King Bhumibol Adulyadej,1927-12-05,69.0,Male,Thailand,NaN,NaN,NaN,NaN,NaN,False,NaN
2,1998,NaN,3.3,Edmond Safra,1932-08-06,65.0,Male,Lebanon,NaN,NaN,NaN,NaN,NaN,True,NaN
3,1999,NaN,1.0,Srichand & Gopichand Hinduja,1935-11-28,NaN,NaN,India,London,NaN,NaN,NaN,NaN,False,NaN
4,1999,NaN,7.1,Dieter Schwarz,1939-09-24,59.0,Male,Germany,Neckarsulm,Fashion & Retail,['Fashion & Retail'],NaN,NaN,True,NaN

In [238]:
print(len(df_billionaire[df_billionaire["rank"].isnull()]))

18

In [239]:
rank_null = df_billionaire[df_billionaire["rank"].isnull()]
rank_null.head(18)

,year,rank,net_worth,full_name,birth_date,age,gender,country_of_citizenship,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
0,1997,NaN,2.0,Chatri Sophonpanich & family,1934-02-28,73.0,Male,Thailand,Bangkok,Finance and Investments,['Finance and Investments'],NaN,NaN,False,NaN
1,1997,NaN,1.8,King Bhumibol Adulyadej,1927-12-05,69.0,Male,Thailand,NaN,NaN,NaN,NaN,NaN,False,NaN
2,1998,NaN,3.3,Edmond Safra,1932-08-06,65.0,Male,Lebanon,NaN,NaN,NaN,NaN,NaN,True,NaN
3,1999,NaN,1.0,Srichand & Gopichand Hinduja,1935-11-28,NaN,NaN,India,London,NaN,NaN,NaN,NaN,False,NaN
4,1999,NaN,7.1,Dieter Schwarz,1939-09-24,59.0,Male,Germany,Neckarsulm,Fashion & Retail,['Fashion & Retail'],NaN,NaN,True,NaN
5,1999,NaN,1.3,Carlos Ardila Lülle,1930-06-04,68.0,Male,Colombia,Bogota,Food and Beverage,['Food and Beverage'],NaN,NaN,True,NaN
6,1999,NaN,2.9,Martin Ebner,1945-08-01,53.0,Male,Switzerland,Wilen,Finance and Investments,['Finance and Investments'],NaN,NaN,False,NaN
7,1999,NaN,1.0,Jose Luis Cutrale,1946-09-17,NaN,Male,Brazil,Sao Paulo,Food and Beverage,['Food and Beverage'],NaN,NaN,True,NaN
8,1999,NaN,1.1,Lee family,NaN,71.0,Male,Hong Kong,Hong Kong,NaN,NaN,NaN,NaN,False,NaN
9,1999,NaN,1.8,Serge Kampf,1934-01-01,65.0,Male,France,NaN,NaN,NaN,NaN,NaN,False,NaN
10,1999,NaN,2.5,Edmond Safra,1932-08-06,66.0,Male,Lebanon,NaN,NaN,NaN,NaN,NaN,True,NaN
11,2000,NaN,1.0,Jose Luis Cutrale,1946-09-17,NaN,Male,Brazil,Sao Paulo,Food and Beverage,['Food and Beverage'],NaN,NaN,True,NaN
12,2000,NaN,1.9,Martin Ebner,1945-08-01,54.0,Male,Switzerland,Wilen,Finance and Investments,['Finance and Investments'],NaN,NaN,False,NaN
13,2000,NaN,4.5,Christoph Henkel,1958-02-11,NaN,NaN,Germany,London,Fashion & Retail,['Fashion & Retail'],NaN,NaN,False,NaN
14,2000,NaN,2.9,Alexander Vik,1955-02-19,45.0,Male,Norway,Monaco,Finance and Investments,['Finance and Investments'],NaN,Investor,False,NaN
15,2000,NaN,1.2,Masahiro Noda,1938-08-24,61.0,Male,Japan,Tokyo,Technology,['Technology'],NaN,NaN,True,NaN
16,2000,NaN,1.2,Kagemasa Kozuki,1940-11-12,59.0,Male,Japan,Tokyo,Technology,['Technology'],NaN,NaN,True,NaN
17,2000,NaN,2.1,Serge Kampf,1934-01-01,66.0,Male,France,NaN,NaN,NaN,NaN,NaN,True,NaN

In [240]:
df_billionaire.loc[(df_billionaire["full_name"] == "Chatri Sophonpanich & family") & (df_billionaire["year"] == 1997), "rank"] = 1.0
df_billionaire.loc[(df_billionaire["full_name"] == "King Bhumibol Adulyadej") & (df_billionaire["year"] == 1997), "rank"] = 2.0

df_billionaire.loc[(df_billionaire["full_name"] == "Edmond Safra") & (df_billionaire["year"] == 1998), "rank"] = 1.0

df_billionaire.loc[(df_billionaire["full_name"] == "Srichand & Gopichand Hinduja") & (df_billionaire["year"] == 1999), "rank"] = 6.0
df_billionaire.loc[(df_billionaire["full_name"] == "Dieter Schwarz") & (df_billionaire["year"] == 1999), "rank"] = 1.0
df_billionaire.loc[(df_billionaire["full_name"] == "Carlos Ardila Lülle") & (df_billionaire["year"] == 1999), "rank"] = 5.0
df_billionaire.loc[(df_billionaire["full_name"] == "Martin Ebner") & (df_billionaire["year"] == 1999), "rank"] = 2.0
df_billionaire.loc[(df_billionaire["full_name"] == "Jose Luis Cutrale") & (df_billionaire["year"] == 1999), "rank"] = 7.0
df_billionaire.loc[(df_billionaire["full_name"] == "Lee family") & (df_billionaire["year"] == 1999), "rank"] = 8.0
df_billionaire.loc[(df_billionaire["full_name"] == "Serge Kampf") & (df_billionaire["year"] == 1999), "rank"] = 4.0
df_billionaire.loc[(df_billionaire["full_name"] == "Edmond Safra") & (df_billionaire["year"] == 1999), "rank"] = 3.0


df_billionaire.loc[(df_billionaire["full_name"] == "Christoph Henkel") & (df_billionaire["year"] == 2000), "rank"] = 1.0
df_billionaire.loc[(df_billionaire["full_name"] == "Alexander Vik") & (df_billionaire["year"] == 2000), "rank"] = 2.0
df_billionaire.loc[(df_billionaire["full_name"] == "Serge Kampf") & (df_billionaire["year"] == 2000), "rank"] = 3.0
df_billionaire.loc[(df_billionaire["full_name"] == "Martin Ebner") & (df_billionaire["year"] == 2000), "rank"] = 4.0
df_billionaire.loc[(df_billionaire["full_name"] == "Masahiro Noda") & (df_billionaire["year"] == 2000), "rank"] = 5.0
df_billionaire.loc[(df_billionaire["full_name"] == "Kagemasa Kozuki") & (df_billionaire["year"] == 2000), "rank"] = 6.0
df_billionaire.loc[(df_billionaire["full_name"] == "Jose Luis Cutrale") & (df_billionaire["year"] == 2000), "rank"] = 7.0

In [241]:
country_null = df_billionaire[df_billionaire["country_of_citizenship"].isnull()]
country_null.head(18)

,year,rank,net_worth,full_name,birth_date,age,gender,country_of_citizenship,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
1074,2004,68.0,5.9,Micky Arison,1949-06-29,54.0,NaN,NaN,Bal Harbour,NaN,['Service'],NaN,NaN,False,Increased
1154,2004,176.0,2.8,Henry Hillman,1918-12-25,85.0,NaN,NaN,Pittsburgh,NaN,['Investments'],NaN,NaN,False,Decreased
1199,2004,231.0,2.3,Charles Butt & family,1938-02-03,65.0,NaN,NaN,San Antonio,NaN,['Fashion and Retail'],NaN,NaN,False,Increased
1305,2004,356.0,1.6,Charles Munger,NaN,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1363,2004,437.0,1.3,Robert McNair,NaN,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1392,2004,472.0,1.2,George Lindemann & family,1936-03-26,67.0,NaN,NaN,Palm Beach,NaN,['Investments'],NaN,NaN,False,Remained Even
1450,2004,552.0,1.0,Dean White,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6919,2011,879.0,1.4,Gabriel Escarrer,1935-03-02,76.0,Male,NaN,Palma de Majorca,NaN,['Service'],NaN,NaN,True,Returned to List
7171,2011,1140.0,1.0,Thomas Bailey,1937-01-01,74.0,Male,NaN,Aspen,NaN,['Finance'],NaN,NaN,True,Remained Even

In [242]:
df_billionaire.loc[(df_billionaire["full_name"] == "Micky Arison") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Henry Hillman") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Charles Butt & family") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Charles Munger") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Robert McNair") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "George Lindemann & family") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Dean White") & (df_billionaire["year"] == 2004), "country_of_citizenship"] = "United States"
df_billionaire.loc[(df_billionaire["full_name"] == "Gabriel Escarrer") & (df_billionaire["year"] == 2011), "country_of_citizenship"] = "Spain"
df_billionaire.loc[(df_billionaire["full_name"] == "Thomas Bailey") & (df_billionaire["year"] == 2011), "country_of_citizenship"] = "United States"

In [243]:
mask = df_billionaire["age"].isnull()

birth_year = pd.to_datetime(df_billionaire.loc[mask, "birth_date"], errors="coerce").dt.year
df_billionaire.loc[mask, "age"] = df_billionaire.loc[mask, "year"] - birth_year

df_billionaire["age"] = df_billionaire["age"].fillna(df_billionaire["age"].mean())
df_billionaire["age"] = df_billionaire["age"].astype(int)
df_billionaire = df_billionaire.drop(columns=["birth_date"])

In [244]:
df_billionaire["age"] = df_billionaire["age"].fillna(df_billionaire["age"].mean().astype(str).split(".")[0])
df_billionaire["age"] = df_billionaire["age"].astype(int)
df_billionaire["rank"] = df_billionaire["rank"].astype(int)
df_billionaire["organization_name"] = df_billionaire["organization_name"].fillna("Unspecified Organization")
df_billionaire["position_in_organization"] = df_billionaire["position_in_organization"].fillna("Unspecified Position")
df_billionaire["wealth_status"] = df_billionaire["wealth_status"].fillna("Unknown")
df_billionaire["gender"] = df_billionaire["gender"].fillna("Group/Family")
df_billionaire["business_category"] = df_billionaire["business_category"].fillna("Unspecified Category")
df_billionaire["business_industries"] = df_billionaire["business_industries"].fillna("['Unspecified']")
df_billionaire["city_of_residence"] = df_billionaire["city_of_residence"].fillna(df_billionaire["country_of_citizenship"])
df_billionaire["self_made"] = df_billionaire["self_made"].astype("boolean")

In [248]:
df_billionaire.tail(20)

,year,rank,net_worth,full_name,age,gender,country_of_citizenship,city_of_residence,business_category,business_industries,organization_name,position_in_organization,self_made,wealth_status
34491,2024,2692,1.0,Mahaveer Prasad Taparia,86,Male,India,Mumbai,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,False,Unknown
34492,2024,2692,1.0,Shivratan Taparia,78,Male,India,Mumbai,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,False,Unknown
34493,2024,2692,1.0,James Truchard,80,Male,United States,Austin,Technology,['Technology'],Unspecified Organization,Unspecified Position,True,Returned to List
34494,2024,2692,1.0,Roy Vagelos,94,Male,United States,Gladstone,Healthcare,['Healthcare'],Unspecified Organization,Unspecified Position,True,Unknown
34495,2024,2692,1.0,Murat Vargi,76,Male,Turkey,Istanbul,Telecom,['Telecom'],Unspecified Organization,Unspecified Position,True,Remained Even
34496,2024,2692,1.0,Wang Yanqing & family,77,Female,China,Weihai,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,False,Decreased
34497,2024,2692,1.0,Scott Watterson,68,Male,United States,Logan,Technology,['Technology'],Unspecified Organization,Unspecified Position,True,Decreased
34498,2024,2692,1.0,Wen Pengcheng & family,61,Male,China,Yunfu,Food & Beverage,['Food & Beverage'],Unspecified Organization,Unspecified Position,True,Remained Even
34499,2024,2692,1.0,Wu Zhongyi,50,Male,China,Xiamen,Technology,['Technology'],Unspecified Organization,Unspecified Position,True,Decreased
34500,2024,2692,1.0,Xu Gang,60,Male,China,Jiaozuo,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,True,Remained Even
34501,2024,2692,1.0,Xu Wanmao,79,Male,China,Ningbo,Service,['Service'],Unspecified Organization,Unspecified Position,True,Decreased
34502,2024,2692,1.0,Xue Jiping,73,Male,China,Nantong,Telecom,['Telecom'],Unspecified Organization,Unspecified Position,True,Decreased
34503,2024,2692,1.0,Yang Yuanqing,59,Male,China,Beijing,Technology,['Technology'],Unspecified Organization,Unspecified Position,True,Returned to List
34504,2024,2692,1.0,"Richard Yuengling, Jr. & family",81,Male,United States,Pottsville,Food & Beverage,['Food & Beverage'],Unspecified Organization,Unspecified Position,False,Remained Even
34505,2024,2692,1.0,Zan Shengda,61,Male,China,Nantong,Diversified,['Diversified'],Unspecified Organization,Unspecified Position,True,Decreased
34506,2024,2692,1.0,Zhang Hong,63,Female,China,Hangzhou,Energy,['Energy'],Unspecified Organization,Unspecified Position,True,Decreased
34507,2024,2692,1.0,Zheng Xiaodong,60,Male,China,Shanghai,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,True,Decreased
34508,2024,2692,1.0,Zhong Sheng Jian,66,Male,Singapore,Singapore,Real Estate,['Real Estate'],Unspecified Organization,Unspecified Position,True,Decreased
34509,2024,2692,1.0,Zhou Junjie,55,Male,China,Hangzhou,Manufacturing,['Manufacturing'],Unspecified Organization,Unspecified Position,True,Unknown
34510,2024,2692,1.0,Zhu Yiwen & family,60,Male,China,Shanghai,Healthcare,['Healthcare'],Unspecified Organization,Unspecified Position,True,Decreased

In [246]:
df_billionaire.isnull().sum()

year                           0
rank                           0
net_worth                      0
full_name                      0
age                            0
gender                         0
country_of_citizenship         0
city_of_residence              0
business_category              0
business_industries            0
organization_name              0
position_in_organization       0
self_made                   3689
wealth_status                  0
dtype: int64

In [247]:
df_billionaire.to_csv("billionaire_cleaned.csv", index=False)